# Generated by Django 3.2 on 2022-09-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_option_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='voters',
            field=models.ManyToManyField(related_name='voted_options', to='voting.AnonymousUser'),
        ),
    ]
