# Generated by Django 3.2.14 on 2022-11-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_poll_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
